services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: alta_user
      POSTGRES_PASSWORD: alta_password
      POSTGRES_DB: alta_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - alta_network
networks:
    alta_network: